// - LOGIN
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_LOGOUT = "LOGIN_LOGOUT";
export const LOGIN_RESET = "LOGIN_RESET";

// - REGISTER
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_RESET = "REGISTER_RESET";

// - TRIPS ALBUM
export const TRIPS_ALBUM_REQUEST = "TRIPS_ALBUM_REQUEST";
export const TRIPS_ALBUM_SUCCESS = "TRIPS_ALBUM_SUCCESS";
export const TRIPS_ALBUM_ERROR = "TRIPS_ALBUM_ERROR";
export const TRIPS_ALBUM_RESET = "TRIPS_ALBUM_RESET";

// - TRIPS ALBUM CREATE
export const TRIPS_ALBUM_CREATE_REQUEST = "TRIPS_ALBUM_CREATE_REQUEST";
export const TRIPS_ALBUM_CREATE_SUCCESS = "TRIPS_ALBUM_CREATE_SUCCESS";
export const TRIPS_ALBUM_CREATE_ERROR = "TRIPS_ALBUM_CREATE_ERROR";
export const TRIPS_ALBUM_CREATE_RESET = "TRIPS_ALBUM_CREATE_RESET";
export const TRIPS_ALBUM_CREATE_GOBACK = "TRIPS_ALBUM_CREATE_GOBACK";

// - TRIPS ALBUM INFO
export const TRIPS_ALBUM_INFO_REQUEST = "TRIPS_ALBUM_INFO_REQUEST";
export const TRIPS_ALBUM_INFO_SUCCESS = "TRIPS_ALBUM_INFO_SUCCESS";
export const TRIPS_ALBUM_INFO_ERROR = "TRIPS_ALBUM_INFO_ERROR";
export const TRIPS_ALBUM_INFO_RESET = "TRIPS_ALBUM_INFO_RESET";

// - TRIPS ALBUM FILES
export const TRIPS_ALBUM_FILES_REQUEST = "TRIPS_ALBUM_FILES_REQUEST";
export const TRIPS_ALBUM_FILES_SUCCESS = "TRIPS_ALBUM_FILES_SUCCESS";
export const TRIPS_ALBUM_FILES_ERROR = "TRIPS_ALBUM_FILES_ERROR";
export const TRIPS_ALBUM_FILES_RESET = "TRIPS_ALBUM_FILES_RESET";

// - HOME LIST INFO
export const HOME_LIST_REQUEST = "HOME_LIST_REQUEST";
export const HOME_LIST_SUCCESS = "HOME_LIST_SUCCESS";
export const HOME_LIST_ERROR = "HOME_LIST_ERROR";
export const HOME_LIST_RESET = "HOME_LIST_RESET";

// - UI
export const UI_REQUEST = "UI_REQUEST";
export const UI_SUCCESS = "UI_SUCCESS";
export const UI_ERROR = "UI_ERROR";
export const UI_RESET = "UI_RESET";

//APPLICATION
export const CHANGE_THEME = "CHANGE_THEME";
export const CHANGE_FONT = "CHANGE_FONT";
export const FORCE_APPEARANCE = "FORCE_APPEARANCE";
export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";

//FRIENDS
export const FRIENDS_LIST_REQUEST = "FRIENDS_LIST_REQUEST";
export const FRIENDS_LIST_SUCCESS = "FRIENDS_LIST_SUCCESS";
export const FRIENDS_LIST_ERROR = "FRIENDS_LIST_ERROR";
export const FRIENDS_LIST_RESET = "FRIENDS_LIST_RESET";

//FRIENDS SEARCH
export const FRIENDS_SEARCH_REQUEST = "FRIENDS_SEARCH_REQUEST";
export const FRIENDS_SEARCH_SUCCESS = "FRIENDS_SEARCH_SUCCESS";
export const FRIENDS_SEARCH_ERROR = "FRIENDS_SEARCH_ERROR";
export const FRIENDS_SEARCH_RESET = "FRIENDS_SEARCH_RESET";

//FRIENDS ADD
export const FRIENDS_ADD_REQUEST = "FRIENDS_ADD_REQUEST";
export const FRIENDS_ADD_SUCCESS = "FRIENDS_ADD_SUCCESS";
export const FRIENDS_ADD_ERROR = "FRIENDS_ADD_ERROR";
export const FRIENDS_ADD_RESET = "FRIENDS_ADD_RESET";

//FRIENDS DELETE
export const FRIENDS_DELETE_REQUEST = "FRIENDS_DELETE_REQUEST";
export const FRIENDS_DELETE_SUCCESS = "FRIENDS_DELETE_SUCCESS";
export const FRIENDS_DELETE_ERROR = "FRIENDS_DELETE_ERROR";
export const FRIENDS_DELETE_RESET = "FRIENDS_DELETE_RESET";
