// - LOGIN
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_LOGOUT = "LOGIN_LOGOUT";
//APPLICATION
export const CHANGE_THEME = "CHANGE_THEME";
export const CHANGE_FONT = "CHANGE_FONT";
export const FORCE_APPEARANCE = "FORCE_APPEARANCE";
export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";
